### ISSUE TITLE
issue with VSX-S510

### ISSUE THREAD

**Issue by oleg77s** [TG908/homebridge-vsx#1]
All AV Recievers, wich work with the iControl AV5 App are supported.
My VSX-S510 is supported by the iControl AV5 too:
ip 192.168.0.160
port: 8102
--------------------------
homebridge config: 
	{
            "accessory": "VSX",
            "name": "VSX-S510",
            "description": "Reciever",
            "ip": "192.168.0.160"         
                    }
---------------------------
Log:  
[2016-11-13 15:58:48] [VSX-S510] Initializing VSX accessory…
handled error
{ Error: connect ECONNREFUSED 192.168.0.160:23
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.0.160',
  port: 23 }
Connection closed
———————————
Port scan 192.168.0.160:

80 HTTP
443 HTTPS
1026 DCOM services
1900 UPNP
8080 Unknown Port Type
8102 Unknown Port Type

There are no open port 23
_______________________

Are you still develop and support this plugin?
Can you help me?

Best Regards

Oleg

**Comment by TG908** [comment]
This plugin works by connecting to port 23. Perhaps Pioneer changed the way the app works with newer devices. Try `telnet 192.168.0.160 8102` on your computer. If you get a connection we might be able to update the plugin to support newer devices

**Comment by oleg77s** [comment]
Trying:
Last login: Thu Nov 17 19:30:57 on ttys002
Mac-mini-olegs:~ oleg$ telnet 192.168.0.160 8102
Trying 192.168.0.160...
Connected to 192.168.0.160.
Escape character is '^]'.

**Comment by oleg77s** [comment]
PO
ICA0
ICA0
RGC100000001000000000000000000000
GBP04
GCP9910000""
GDP000010000100001
GEP01000""
GEP02000""
GEP03000""
GEP04000""
FN17
PWR0
ICA0
RGC100000001000000000000000000000
VOL053
FN25
VD 
VOL051
VU
VOL053
PF
PWR2

working :)

**Comment by TG908** [comment]
I am going to update the plugin to support different ports. Let me now if this change works for you.

**Comment by oleg77s** [comment]
On/Off is ok now, thank you.

**Comment by TG908** [comment]
Great
