### ISSUE TITLE
VSX-925, No functionality

### ISSUE THREAD

**Issue by ryankpeters1** [TG908/homebridge-vsx#4]
I have this setup on my homebridge, and my receiver (VSX-925) is setup as port 8102 (port 23 is closed).
The only thing that works is when the receiver is on, HomeKit displays it is on.
When the receiver is off, HomeKit displays "No Response"
When I try to turn the receiver off or on using HomeKit, it does nothing.

**Comment by TG908** [comment]
The plugin is not able to detect the current device state at this point in time. The displayed state only represents the last state the device was set to with homekit.
